import type { CampaignManifest } from "@pitchflow/core";

export function renderCopyMarkdown(manifest: CampaignManifest): string {
  return `# ${manifest.productBrief.productName} launch copy

Generated by PitchFlow from commit \`${manifest.source.commitSha}\`.

## X

${manifest.copy.x}

## LinkedIn

${manifest.copy.linkedIn}

## Product Hunt

**Name:** ${manifest.copy.productHunt.name}

**Tagline:** ${manifest.copy.productHunt.tagline}

${manifest.copy.productHunt.description}

### First comment

${manifest.copy.productHunt.firstComment}

## Email

**Subject:** ${manifest.copy.email.subject}

${manifest.copy.email.body}

## Headline variants

${manifest.copy.headlineVariants.map((headline) => `- ${headline}`).join("\n")}

## CTA variants

${manifest.copy.ctaVariants.map((cta) => `- ${cta}`).join("\n")}
`;
}
